### ISSUE TITLE
hello, I got several questions

### ISSUE THREAD

**Issue by pak24** [cosimoiaia/KERAS-Show-and-Tell#1]
in the file Show-and-Tell.py, 
first, the line 26 the redefinition, 
second, the line 136, 'path=images+str(img)' , undefined name 'images' , and the same problems in the line 198, 202, 206,
third, in the line 209, 'images_path =[]' , 'images_path' is assigned to but never used,
over all, that is my all questions, 
I really look forword to your answers, thank you very much.

**Comment by cosimoiaia** [comment]
Hi, 
thanks for warning me, 
there were typos I made in moving the code from colab to github (images/images_path), I fixed it now. 

Cheers.
