### ISSUE TITLE
sorry， I want to ask you another question.

### ISSUE THREAD

**Issue by pak24** [cosimoiaia/KERAS-Show-and-Tell#3]
I run the Show-and-Tell.py, at first ,everything is fine ,but in line 319,and in the function predict_captions , in line 257,there is a error called KeyError: '667626_18933d713e.jpg'  

I really do not understand this error, so i search is on the internet, and i found the reason for this error is there is no key in the dict, so i thought in line 257 encoding_test is a dict , and i found the dict's first apperance is in line 143, in line 143, the code open a file named 'encoded_test_images_inceptionV3.p' , so i wonder what is this file ?  can you provide some explaination?  thank you very much!

**Comment by cosimoiaia** [comment]
Hi, 
the file contains the vectors of encoded images by inceptionv3 specifically the ones from the test set.

Cheers.

**Comment by pak24** [comment]
I do't really understand , can you explain more ?
thank you very much.
